# Generated by Django 4.0.1 on 2022-01-08 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='events',
            new_name='Slider',
        ),
    ]
