# Generated by Django 4.0.1 on 2022-01-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_rename_events_slider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='eventdetail',
            new_name='subtext',
        ),
        migrations.AlterField(
            model_name='slider',
            name='pic',
            field=models.ImageField(upload_to='media/sliders/'),
        ),
    ]
