# Generated by Django 4.0.1 on 2022-01-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='order_status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
